// 3-week progression block: 7-27 Sep 2026. Evaluation: 28 Sep-4 Oct.
const SEP26_PHASE={start:"2026-09-07",end:"2026-09-27",evalStart:"2026-09-28",evalEnd:"2026-10-04"};
const PSTR=(key,name,sets,min,max,rir,rest,muscle,note)=>({key,name,type:"strength",sets,min,max,rir,rest,muscle,note});
const PMOB=(key,name,group,dose,note)=>({key,name,type:"mobility",group,dose,note});
function sep26InRange(date,a=SEP26_PHASE.start,b=SEP26_PHASE.evalEnd){return date>=a&&date<=b}
function sep26Active(date=currentDate()){return state.settings.mode==="season"&&sep26InRange(date)}
function sep26Week(date=currentDate()){if(!sep26InRange(date))return 0;if(date<="2026-09-13")return 1;if(date<="2026-09-20")return 2;if(date<="2026-09-27")return 3;return 4}
function sep26WeekTitle(date=currentDate()){return ({1:"Semana 1 · Referencia y técnica",2:"Semana 2 · Progresión de repeticiones",3:"Semana 3 · Sobrecarga y consolidación",4:"Semana de evaluación · Mantener y medir"})[sep26Week(date)]||""}
function sep26WeekFocus(date=currentDate()){return ({1:"Encuentra cargas reproducibles y clava el RIR. No añadas series ni persigas récords el primer día.",2:"Mantén la carga y busca alguna repetición adicional sin salir del RIR. Si ya estabas en el techo, sigue la recomendación del ejercicio.",3:"Si confirmaste el techo del rango en dos sesiones comparables, sube el menor incremento disponible y vuelve al extremo bajo de repeticiones. Si no, conserva carga y suma reps.",4:"Mantén ejercicios, volumen y técnica. No añadas series: queremos medir el bloque antes de cambiar octubre."})[sep26Week(date)]||""}

const SEP26_PLANS={
"0":{key:"sep26_rest",title:"Descanso + recuperación",type:"rest",subtitle:"Movilidad completa y core en el complemento",exercises:[]},
"1":{key:"sep26_swim_mon",title:"Natación",type:"swim",subtitle:"Sesión del entrenador · complemento estético 16–17 h",exercises:[]},
"2":{key:"sep26_a",title:"Gym A",type:"gym",subtitle:"Full body · fuerza, pectoral superior, cuádriceps e isquios",exercises:[
PMOB("med_ball_chest_pass","Lanzamiento de balón medicinal al pecho","Potencia","3 × 3 · 60–90 s","Máxima velocidad y cero fatiga acumulada. Cada repetición explosiva y limpia; aquí sí descansa 60–90 s aunque no haya cronómetro automático."),
PSTR("hack_squat","Hack squat",3,5,8,"1–2","3 min","Cuádriceps + glúteo","Baja 2–3 s con ROM profundo y pelvis estable; desde abajo intenta acelerar sin rebotar."),
PSTR("incline_db_press","Press inclinado con mancuernas · ~30°",3,6,8,"1–2","2–3 min","Pectoral superior + deltoide anterior","Prioridad pectoral superior. Escápulas estables, estiramiento controlado y concéntrica con intención rápida."),
PSTR("chest_supported_row","Remo con pecho apoyado",3,6,10,"1–2","2–3 min","Espalda","Estable para no sumar fatiga inútil a la natación: pecho apoyado, sin impulso lumbar; tira fuerte y controla la vuelta."),
PSTR("seated_leg_curl","Curl femoral sentado",3,8,12,"1–2","2 min","Isquios","Aprovecha la posición alargada; pausa breve en flexión y excéntrica controlada."),
PSTR("cable_lateral_raise","Elevación lateral en polea",3,12,20,"1–2","90 s","Deltoide lateral","Hipertrofia pura: hombro estable y sin balanceo. No hace falta moverla explosivamente."),
PSTR("cable_crunch","Crunch en polea",3,8,15,"1–2","90 s","Core","Hipertrofia abdominal: acerca costillas a pelvis flexionando el tronco; no lo conviertas en una bisagra de cadera.")]},
"3":{key:"sep26_swim_wed",title:"Natación",type:"swim",subtitle:"Sesión del entrenador · movilidad media 16–17 h",exercises:[]},
"4":{key:"sep26_b",title:"Gym B",type:"gym",subtitle:"Full body · cadena posterior, pectoral, deltoide posterior y core",exercises:[
PSTR("rdl","Peso muerto rumano",3,5,8,"1–2","3 min","Glúteo + isquios","Excéntrica controlada y gran tensión en cadena posterior; subida potente, pero no balística."),
PSTR("pull_up","Dominadas / jalón al pecho",3,6,10,"1–2","2–3 min","Espalda + bíceps","Concéntrica fuerte, excéntrica controlada y sin balanceo. La natación ya aporta mucho tirón: calidad antes que más series."),
PSTR("leg_press","Prensa",3,8,12,"1–2","3 min","Cuádriceps + glúteo","ROM amplio y pelvis estable. Sube con intención rápida sin bloquear violentamente las rodillas."),
PSTR("machine_chest_press","Press de pecho en máquina",3,8,12,"1–2","2 min","Pectoral + deltoide anterior","Hipertrofia estable del pectoral global; trayectoria cómoda para hombro. No hace falta hacerlo balístico."),
PSTR("reverse_pec_deck","Reverse pec-deck",3,12,20,"1–2","90 s","Deltoide posterior","Prioridad deltoide posterior. Abre con control sin convertirlo en otro remo."),
PSTR("biceps_curl","Curl de bíceps",2,8,12,"1–2","90 s","Bíceps","Estable, sin balanceo y con recorrido completo."),
PSTR("standing_calf","Gemelo de pie",3,8,12,"1–2","90–120 s","Gemelos","Estiramiento real abajo, pausa breve y subida completa. Sin rebotes."),
PSTR("ab_wheel","Ab wheel",3,6,12,"1–2","90–120 s","Core","Anti-extensión. Si es corporal registra 0 kg; progresa con reps y recorrido manteniendo costillas abajo y pelvis estable."),
PSTR("pallof_press","Pallof press",2,10,15,"2","60–90 s","Core","Anti-rotación: pelvis y caja torácica quietas. No persigas peso a costa de girarte.")]},
"5":{key:"sep26_swim_fri",title:"Natación",type:"swim",subtitle:"Sesión del entrenador · movilidad corta 16–17 h",exercises:[]},
"6":{key:"sep26_c",title:"Gym C",type:"gym",subtitle:"Full body completo · hipertrofia prioritaria + potencia",exercises:[
PMOB("vertical_jump","Salto vertical","Potencia","3 × 3 · 60–90 s","Solo si llegas fresco. Máxima velocidad, aterrizaje limpio y parada antes de que caiga la altura; descansa 60–90 s aunque no haya cronómetro automático."),
PSTR("hip_thrust","Hip thrust",3,6,8,"1–2","2–3 min","Glúteo","Subida con intención explosiva, pausa 1 s arriba sin hiperextender lumbar y bajada controlada."),
PSTR("incline_smith_press","Press inclinado en Smith · ~30°",3,8,10,"1–2","2–3 min","Pectoral superior + deltoide anterior","Segundo estímulo específico del pectoral superior. Máxima estabilidad y progresión reproducible."),
PSTR("seated_cable_row","Remo sentado en polea",2,8,12,"1–2","2 min","Espalda","Volumen contenido por las tres nataciones. Estricto, estable y sin impulso."),
PSTR("machine_shoulder_press","Press de hombro en máquina",2,6,10,"2","2 min","Deltoide anterior","Estímulo directo del deltoide anterior. Máquina estable, sin arquear; empuja con intención rápida y controla la bajada."),
PSTR("leg_extension","Extensión de cuádriceps",4,10,15,"1–2","90 s","Cuádriceps","Hipertrofia pura: pausa arriba y excéntrica controlada. No hace falta hacerlo explosivo."),
PSTR("leg_curl","Curl femoral",3,10,15,"1–2","2 min","Isquios","Preferencia por sentado si está disponible; controla la fase alargada y evita rebotes."),
PSTR("lateral_raise","Elevación lateral",3,12,20,"1–2","90 s","Deltoide lateral","Hipertrofia estable: deltoide lateral, no trapecio. Sin impulso."),
PSTR("standing_calf_sat","Gemelo de pie",2,10,15,"1–2","90 s","Gemelos","ROM completo, estiramiento real y pausa. Sin rebotes."),
PSTR("overhead_triceps","Tríceps por encima de la cabeza",2,10,15,"1–2","90 s","Tríceps","Hipertrofia estable en longitud larga. Puedes acercarte al RIR objetivo porque el domingo no nadas."),
PSTR("hanging_knee_raise","Elevación de rodillas / piernas colgado",3,8,15,"1–2","90 s","Core","Compresión + recto abdominal. Si es corporal registra 0 kg; termina llevando pelvis hacia costillas, no solo flexionando cadera."),
PMOB("sat_couch","Couch stretch","Cadera/cuádriceps","1 × 45 s por lado","Glúteo contraído y pelvis neutra; reduce el rango si arqueas la zona lumbar."),
PMOB("sat_adductor","Adductor rockback","Cadera/aductores","1 × 10 por lado","Pierna abierta lateralmente; lleva la cadera atrás lentamente y sin rebotes."),
PMOB("sat_lat","Estiramiento dorsal","Dorsal/hombro","1 × 45 s por lado","Brazo largo y cadera atrás; tensión suave, nunca dolor anterior de hombro."),
PMOB("sat_pec","Estiramiento suave de pectoral","Pectoral/hombro","1 × 30 s por lado","Gira el tronco suavemente sin empujar el hombro hacia delante."),
PMOB("sat_open","Open book","Torácica","1 × 8 por lado","Rodillas juntas y pelvis quieta; abre desde columna torácica.")]}}
;
const sep26OldPlanFor=planFor;
planFor=function(date){return sep26Active(date)?(SEP26_PLANS[String(weekday(date))]||sep26OldPlanFor(date)):sep26OldPlanFor(date)};

const SEP26_COMPLEMENTS={
"0":{key:"sep26_sun_mobility",title:"Movilidad completa + faja abdominal",timing:"Domingo · 30–40 min · baja fatiga",note:"Día principal de movilidad. Calidad, respiración y control; no persigas dolor ni rangos extremos. No se usa cronómetro de descanso.",exercises:[
PMOB("sun_knee","Knee-to-wall","Tobillo","2 × 10 + 30 s por lado","Talón apoyado; lleva la rodilla hacia delante siguiendo el pie sin colapsar el arco."),PMOB("sun_squat","Sentadilla profunda asistida","Tobillo/cadera","2 × 45–60 s","Usa apoyo si mejora la posición. Talones apoyados y pequeños desplazamientos sin rebotes."),PMOB("sun_9090","90/90 switches","Cadera","2 × 8 por lado","Cambia ambas rodillas de lado con control; intenta no ayudarte con las manos."),PMOB("sun_couch","Couch stretch","Cadera/cuádriceps","2 × 45 s por lado","Glúteo contraído y pelvis neutra; reduce rango si arqueas lumbar."),PMOB("sun_add","Adductor rockback","Cadera/aductores","2 × 10 por lado","Una pierna extendida lateralmente; lleva la cadera atrás despacio."),PMOB("sun_open","Open book","Torácica","2 × 8 por lado","Rodillas juntas; rota tórax sin dejar que la pelvis acompañe."),PMOB("sun_tspine","Extensión torácica sobre foam roller","Torácica","2 × 6–8","Rodillo en espalda media/alta; extiende tórax con abdomen activo para no compensar con lumbar."),PMOB("sun_lat","Estiramiento dorsal","Dorsal/hombro","2 × 45 s por lado","Cadera atrás y brazo largo; tensión suave, no pinzamiento."),PMOB("sun_wall","Wall slides","Hombro/escápula","2 × 10","Antebrazos contra pared; sube sin arquear lumbares ni encoger hombros."),PMOB("sun_scap","Scapular push-up / push-up plus","Serrato/escápula","2 × 12–15","Codos extendidos; separa escápulas al final sin convertirlo en una flexión normal."),PMOB("sun_rot","Rotación externa con banda","Manguito rotador","2 × 15–20","Ligera, ~5 RIR. Codo pegado al costado y hombro lejos de la oreja."),PMOB("sun_pec","Estiramiento de pectoral en marco","Pectoral/hombro","2 × 30–45 s por lado","Tensión suave; para si aparece dolor o pinzamiento anterior."),PMOB("sun_dead","Dead bug","Core · anti-extensión","2 × 8–10 por lado","Lumbar suavemente pegada al suelo y costillas abajo; extiende solo hasta mantener pelvis estable."),PMOB("sun_side","Plancha lateral","Core · anti-flexión lateral","2 × 30–45 s por lado","Cuerpo en línea, glúteos activos y pelvis alta. No hace falta llegar al fallo.")]},
"1":{key:"sep26_mon_extra",title:"Complementario estético + movilidad corta",timing:"Ideal 16–17 h · natación 22–23 h",note:"Accesorios de baja fatiga sistémica. Mantén margen en brazos para llegar fresco a la piscina.",exercises:[PSTR("seated_calf","Gemelo sentado",3,10,15,"1–2","90 s","Gemelos","Baja lento, pausa en estiramiento y sube completamente; sin rebotes."),PSTR("cable_curl","Curl de bíceps en polea",3,10,15,"2–3","90 s","Bíceps","Antes de nadar: estable, sin balanceo y sin fallo."),PSTR("triceps_pushdown","Extensión de tríceps en polea",3,10,15,"2–3","90 s","Tríceps","Codos estables y extensión completa; nada de fallo antes de piscina."),PSTR("hip_abduction","Abducción de cadera",4,12,20,"1–2","60–90 s","Glúteo medio","Pausa en apertura, pelvis estable y vuelta controlada."),PMOB("mon_rot","Rotación externa con banda","Manguito rotador","2 × 15–20","Muy suave, ~5 RIR. Codo junto al costado."),PMOB("mon_wall","Wall slides","Hombro/escápula","2 × 10","Sube sin arquear lumbares ni encoger hombros."),PMOB("mon_open","Open book","Torácica","1 × 8 por lado","Rodillas juntas y pelvis quieta; gira desde tórax."),PMOB("mon_lat","Estiramiento dorsal","Dorsal/hombro","1 × 30–45 s por lado","Tensión suave, no pinzamiento."),PMOB("mon_pec","Estiramiento suave de pectoral","Pectoral/hombro","1 × 30 s por lado","Giro suave del tronco, sin adelantar el hombro.")]},
"3":{key:"sep26_wed_mob",title:"Movilidad media",timing:"Ideal 16–17 h · natación 22–23 h · 15–20 min",note:"Recuperar rango y control entre Gym A y Gym B; no generar fatiga.",exercises:[PMOB("wed_knee","Knee-to-wall","Tobillo","2 × 10 por lado","Talón pegado al suelo y rodilla siguiendo los dedos."),PMOB("wed_9090","90/90 switches","Cadera","2 × 8 por lado","Cambia de lado lentamente y sin rebotes."),PMOB("wed_add","Adductor rockback","Cadera/aductores","2 × 10 por lado","Cadera atrás con una pierna lateral; no fuerces el final."),PMOB("wed_open","Open book","Torácica","2 × 8 por lado","Rodillas juntas y rotación desde tórax."),PMOB("wed_wall","Wall slides","Hombro/escápula","2 × 10","Costillas controladas y hombros lejos de orejas."),PMOB("wed_rot","Rotación externa con banda","Manguito rotador","2 × 15–20","Ligera, ~5 RIR. No busques congestión."),PMOB("wed_face","Face pull ligero + rotación externa","Escápula/deltoide posterior","2 × 15–20","Muy poco peso; control y resistencia, no fallo.")]},
"5":{key:"sep26_fri_mob",title:"Movilidad corta",timing:"Ideal 16–17 h · natación 22–23 h · 10–12 min",note:"Microdosis para llegar suelto a la piscina sin fatiga.",exercises:[PMOB("fri_wall","Wall slides","Hombro/escápula","2 × 10","Sin arquear lumbares ni encoger hombros."),PMOB("fri_rot","Rotación externa con banda","Manguito rotador","2 × 15–20","Resistencia ligera y mucho margen."),PMOB("fri_open","Open book","Torácica","1 × 8 por lado","Rodillas juntas y rotación torácica."),PMOB("fri_knee","Knee-to-wall","Tobillo","1 × 10 por lado","Talón apoyado y movimiento lento."),PMOB("fri_lat","Estiramiento dorsal","Dorsal/hombro","1 × 30–45 s por lado","Tensión suave, sin pinzamiento."),PMOB("fri_pec","Estiramiento suave de pectoral","Pectoral/hombro","1 × 30 s por lado","Giro suave, sin forzar el hombro.")]}}
;
const sep26OldComplement=seasonComplementTemplate;
seasonComplementTemplate=function(date=currentDate()){return sep26Active(date)?(SEP26_COMPLEMENTS[String(weekday(date))]||null):sep26OldComplement(date)};

const sep26OldAdvice=exerciseAdvice;
exerciseAdvice=function(e){const base=sep26OldAdvice(e),w=sep26Week(currentDate());if(!w||e.type==="mobility")return base;const p={1:"Semana 1: fija una referencia reproducible. ",2:"Semana 2: prioriza sumar repeticiones con la misma carga. ",3:"Semana 3: sube carga solo si la doble progresión está confirmada; al subir, vuelve al extremo bajo de reps. ",4:"Evaluación: mantén volumen y técnica; no añadas series antes de revisar el bloque. "}[w];return p+base};
function sep26RulesHTML(date=currentDate()){if(!sep26Active(date))return"";return `<div class="card"><div class="eyebrow">Ciclo 3 semanas · septiembre 2026</div><div class="hero-title" style="font-size:18px">${esc(sep26WeekTitle(date))}</div><div class="callout" style="margin-top:8px">${esc(sep26WeekFocus(date))}</div><details style="margin-top:10px"><summary>Reglas de progresión</summary><div class="subtitle" style="margin-top:8px"><strong>Subir peso:</strong> cuando completes el techo del rango en todas las series con el RIR previsto en dos sesiones comparables, usa el menor salto disponible (orientación 2–10%) y vuelve al mínimo de reps.<br><br><strong>Subir reps:</strong> es la progresión por defecto mientras no hayas confirmado el techo del rango.<br><br><strong>Bajar peso:</strong> si caes por debajo del mínimo o el RIR real es menor que el objetivo pese a descansar bien, mantén o reduce un pequeño paso.<br><br><strong>Subir series:</strong> no es la progresión por defecto en este bloque. El volumen se mantiene estable para poder interpretar el resultado; se reconsidera tras el informe final.<br><br><strong>Dolor/fatiga:</strong> no compenses una mala serie añadiendo volumen.</div></details><div class="subtitle" style="margin-top:10px">Evaluación: 28 sep–4 oct. Medición final ideal: domingo 4 de octubre en las mismas condiciones del pesaje habitual.</div></div>`}
const sep26OldRenderWorkout=renderWorkout;
renderWorkout=function(){sep26OldRenderWorkout();const root=document.getElementById("viewWorkout"),html=sep26RulesHTML(currentDate());if(root&&html)root.insertAdjacentHTML("afterbegin",html)};

function sep26ReportEnd(){return todayISO()<SEP26_PHASE.evalEnd?todayISO():SEP26_PHASE.evalEnd}
function sep26Rows(rows,a=SEP26_PHASE.start,b=sep26ReportEnd()){return (rows||[]).filter(x=>x?.date>=a&&x?.date<=b)}
function sep26LatestBody(date){return [...(state.body||[])].filter(x=>x.date<=date).sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function sep26Delta(a,b){return Object.fromEntries(["weight","waist","chest","arm","hips","thigh","calf"].map(k=>[k,a?.[k]!=null&&b?.[k]!=null&&a[k]!==""&&b[k]!==""?+(+b[k]-+a[k]).toFixed(2):null]))}
function sep26Avg(rows,k){const v=rows.map(x=>+x?.[k]).filter(Number.isFinite);return v.length?+(v.reduce((a,b)=>a+b,0)/v.length).toFixed(2):null}
function sep26Completed(end){return [...(state.sessions||[]),...(state.extraSessions||[])].filter(s=>s?.completed&&s.date>=SEP26_PHASE.start&&s.date<=end)}
function sep26ExerciseProgress(end){if(typeof strengthChartGroups!=="function")return[];return strengthChartGroups(end).map(g=>{const p=g.points.filter(x=>x.date>=SEP26_PHASE.start&&x.date<=end);if(!p.length)return null;const a=p[0],b=p.at(-1);return{key:g.exercise.key,exercise:g.exercise.name,loadConvention:typeof loadLabel==="function"?loadLabel(g.exercise):null,first:a,last:b,maxLoadChangeKg:+(b.left-a.left).toFixed(2),maxLoadChangePct:a.left?+((b.left-a.left)/a.left*100).toFixed(2):null,sessions:p.length,points:p}}).filter(Boolean)}
function sep26Weeks(end){return [["Semana 1","2026-09-07","2026-09-13"],["Semana 2","2026-09-14","2026-09-20"],["Semana 3","2026-09-21","2026-09-27"],["Evaluación","2026-09-28","2026-10-04"]].filter(([,a])=>a<=end).map(([label,a,b])=>{const z=b<end?b:end,s=[...(state.sessions||[]),...(state.extraSessions||[])].filter(x=>x?.completed&&x.date>=a&&x.date<=z),sw=(state.swim||[]).filter(x=>x?.completed&&x.date>=a&&x.date<=z),d=(state.daily||[]).filter(x=>x.date>=a&&x.date<=z);return{label,start:a,end:z,completedStrengthOrExtraSessions:s.length,completedSwims:sw.length,swimMeters:sw.reduce((n,x)=>n+(+x.meters||0),0),effectiveStrengthSets:typeof strengthSeriesCount==="function"?strengthSeriesCount(s):null,avgSessionRPE:typeof avgRPEFor==="function"?avgRPEFor(s):null,avgEnergy:sep26Avg(d,"energy"),avgFatigue:sep26Avg(d,"fatigue"),avgPain:sep26Avg(d,"pain"),avgSleep:sep26Avg(d,"sleep"),checkins:d.length}})}
function buildSep26Report(){const end=sep26ReportEnd(),baseline=sep26LatestBody(SEP26_PHASE.start),latest=sep26LatestBody(end),body=sep26Rows(state.body,"2026-09-01",end),daily=sep26Rows(state.daily,SEP26_PHASE.start,end),swim=sep26Rows(state.swim,SEP26_PHASE.start,end),foods=sep26Rows(state.foods,SEP26_PHASE.start,end),nutrition=[...new Set(foods.map(x=>x.date))].sort().map(date=>({date,...dayNutrition(date)})),sessions=sep26Completed(end);return{app:"Training Lab",reportVersion:1,reportType:"sep-2026-three-week-block",generatedAt:new Date().toISOString(),phase:{...SEP26_PHASE,availableThrough:end},progressionLogic:{method:"double progression",loadIncrease:"Smallest available increment (orientation 2–10%) after two comparable sessions with all prescribed sets at the top of the rep range and programmed RIR; then reset to the low end of reps.",reps:"Otherwise keep load and add reps while preserving technique and RIR.",loadReduction:"Maintain or reduce a small step if reps fall below the minimum or RIR is lower than programmed after adequate rest.",sets:"Held stable during the three training weeks; volume changes are reserved for post-block review."},body:{baseline,latest,delta:sep26Delta(baseline,latest),records:body},weekly:sep26Weeks(end),recovery:{records:daily,avgEnergy:sep26Avg(daily,"energy"),avgFatigue:sep26Avg(daily,"fatigue"),avgPain:sep26Avg(daily,"pain"),avgSleep:sep26Avg(daily,"sleep")},swimming:{records:swim,totalMeters:swim.reduce((n,x)=>n+(+x.meters||0),0),avgRPE:sep26Avg(swim,"rpe"),avgShoulderPain:sep26Avg(swim,"pain")},nutrition:{goals:state.settings.nutritionGoals||{},days:nutrition,rawEntries:foods},performance:{exerciseProgress:sep26ExerciseProgress(end),completedSessions:sessions},photos:{metadata:state.photoMonths||[],note:"Las imágenes se guardan en IndexedDB y no se incluyen en el JSON."},appSettings:{mode:state.settings.mode,planName:state.settings.planName||null}}}
function downloadSep26Report(){download(`Training_Lab_informe_${SEP26_PHASE.start}_a_${SEP26_PHASE.evalEnd}.json`,JSON.stringify(buildSep26Report(),null,2),"application/json");toast("Informe completo descargado")}
function sep26ReportHTML(){const r=buildSep26Report(),d=r.body.delta,summary=[d.weight!=null?`peso ${d.weight>=0?"+":""}${d.weight} kg`:null,d.waist!=null?`cintura ${d.waist>=0?"+":""}${d.waist} cm`:null].filter(Boolean).join(" · "),final=todayISO()>=SEP26_PHASE.evalStart;return `<div class="section">Informe del ciclo</div><div class="card"><div class="row between settings-status-row"><div><strong>${final?"Evaluación del bloque":"Informe en construcción"}</strong><small>Datos hasta ${esc(r.phase.availableThrough)}${summary?` · ${esc(summary)}`:""}</small></div><span class="pill ${final?"good":""}">${final?"Evaluar":"3 semanas"}</span></div><div class="subtitle" style="margin-top:10px">Incluye peso, cintura y perímetros; energía, fatiga, dolor y sueño; natación; nutrición; sesiones, series y evolución de cargas/repeticiones por ejercicio y equipo. Las fotos no se incrustan.</div><div class="actions" style="margin-top:10px"><button class="btn" onclick="downloadSep26Report()">Descargar informe completo</button></div><div class="callout" style="margin-top:10px">Revisión final: 28 sep–4 oct. Idealmente añade la medición final el domingo 4 de octubre antes de descargar el informe definitivo.</div></div>`}
const sep26OldRenderProgress=renderProgress;
renderProgress=function(){sep26OldRenderProgress();const root=document.getElementById("viewProgress");if(root)root.insertAdjacentHTML("afterbegin",sep26ReportHTML())};
